Dz0
JerryMann/SkurkoAndroidPvt pull request #1
Opened 2019-06-15 19:20 UTC by JerryMann

2019-06-16 08:35 UTC, tim-teacher requested changes
Нужно добавить ссылочку на сайте и нажать на "Отправить на проверку" только после этого проверяется.

2019-06-16 11:41 UTC, eugenia-shumeiko commented on app/src/main/java/by/itacademy/pvt/skurkoandroidpvt/MainActivity.kt
> +            findViewById<TextView>(R.id.textView1).setText(text1)
Слишком дорогая операция, чтобы делать ее каждый раз при клике на кнопку. Лучше сохранить ее в переменную.

2019-06-16 11:42 UTC, eugenia-shumeiko commented on app/src/main/java/by/itacademy/pvt/skurkoandroidpvt/MainActivity.kt
> +        findViewById<TextView>(R.id.textView1).setOnClickListener {
Дублирование кода. Стоит вынести в отдельный метод.

2019-06-16 12:08 UTC, 3RUN approved these changes

2019-06-16 12:08 UTC, 3RUN commented on app/src/main/java/by/itacademy/pvt/skurkoandroidpvt/MainActivity.kt
> +class MainActivity : Activity() {
Классы, связанные с ДЗ, должны начинаться с Dz0, например Dz0Activity. Т.е. должен быть класс (и файл) Dz0Activity, вместо MainActivity и так для всех последующих д/з. Соответственно, нужно будет и в манифесте и везде поменять названия на Dz0Activity.

2019-06-16 12:08 UTC, 3RUN commented on app/src/main/java/by/itacademy/pvt/skurkoandroidpvt/MainActivity.kt
>          setContentView(R.layout.activity_main)
Layout соответственно тоже рекомендовал бы под каждую д/з делать отдельно, с соответствующим названием. Плюс по названиями layout, название должно быть как активити, но наоборот. Т.е. activity_dz0 (если активити называется Dz0Activity).

2019-06-16 13:56 UTC, tim-teacher requested changes
Поправьте замечания которые вам дали

2019-06-16 13:56 UTC, jushlwest commented on app/src/main/res/layout/activity_main.xml
> +
две пустых строки

2019-06-16 13:56 UTC, jushlwest commented on app/src/main/res/layout/activity_main.xml
> +
опять пустые строки

2019-06-16 13:56 UTC, jushlwest commented on app/src/main/java/by/itacademy/pvt/skurkoandroidpvt/MainActivity.kt
> +
2 пустые строки

2019-06-16 13:56 UTC, jushlwest commented on app/src/main/java/by/itacademy/pvt/skurkoandroidpvt/MainActivity.kt
> +            findViewById<TextView>(R.id.textView1).setText(text1)
Верно, делать findViewById нужно тольк один раз при создании активити

2019-06-16 13:56 UTC, jushlwest commented on app/src/main/java/by/itacademy/pvt/skurkoandroidpvt/MainActivity.kt
> +class MainActivity : Activity() {
Все верно, активити для меню можете только назвать каким то общим названием.

2019-06-16 15:54 UTC, eugenia-shumeika approved these changes

2019-06-16 15:54 UTC, eugenia-shumeika commented on app/src/main/java/by/itacademy/pvt/skurkoandroidpvt/MainActivity.kt
> +        findViewById<TextView>(R.id.textView2).setOnClickListener {
Снова дублирование.

2019-06-17 11:07 UTC, JerryMann reviewed
Выполнил все пожелания! Спасибо за ревью)

2019-06-18 11:22 UTC, tim-teacher requested changes
Нужно еще поправить

2019-06-18 11:22 UTC, jushlwest commented on app/src/main/java/by/itacademy/pvt/skurkoandroidpvt/Dz0activity.kt
> +        fun swapValues() {
метод внутри другого метода? :)

2019-06-18 11:22 UTC, jushlwest commented on app/src/main/java/by/itacademy/pvt/skurkoandroidpvt/Dz0activity.kt
> +        var text1 = R.string.fizz
а зачем это? если можно просто местами менять данные и задать их в xml, тогда и когда получится меньше

2019-06-18 13:44 UTC, eugenia-shumeika approved these changes

2019-06-18 13:45 UTC, JerryMann commented
Сделал последние исправления

2019-06-22 09:13 UTC, tim-teacher approved these changes

2019-06-22 10:04 UTC, merged