Dz11
JerryMann/SkurkoAndroidPvt pull request #10
Opened 2019-07-23 16:42 UTC by JerryMann

2019-07-24 10:56 UTC, 3RUN approved these changes

2019-07-25 22:40 UTC, tim-teacher requested changes

2019-07-25 22:40 UTC, jushlwest commented on app/src/main/java/by/itacademy/pvt/skurkoandroidpvt/dz11/dzMVP/Dz11DetailPresenter.kt
> +        view?.getDetails(student)
странный get который не возвращает данные, я так понимаю тут должен быть showStudent().

2019-07-25 22:40 UTC, jushlwest commented on app/src/main/java/by/itacademy/pvt/skurkoandroidpvt/dz11/dzMVP/Dz11EditFragment.kt
> +            if (newUrl.isEmpty() ||
все проверки выносите в презентер

2019-07-25 22:40 UTC, jushlwest commented on app/src/main/java/by/itacademy/pvt/skurkoandroidpvt/dz11/dzMVP/Dz11EditFragment.kt
> +            dz8_urlEditText.setText(student.imageUrl)
java конвеншены...

2019-07-25 22:40 UTC, jushlwest commented on app/src/main/java/by/itacademy/pvt/skurkoandroidpvt/dz11/dzMVP/Dz11ListFragment.kt
> +        prefManager = Dz8PrefManager(requireContext())
хорошо бы это тоже в презентер вынести, он же у нас логикой занимается, а контектст можно глобальный взять.

2019-07-25 22:40 UTC, jushlwest commented on app/src/main/java/by/itacademy/pvt/skurkoandroidpvt/dz11/dzMVVM/Dz11State.kt
> +    object Loaded : Dz11State()
лучше конечно лист передавать тут, что бы логика была более прямая так сказать. А то выходит что сообщения отдельно, отдельно еще сами дергаете VM что бы узнать естли данные, тоесть фактически у вас логика в активити

2019-07-27 21:04 UTC, tim-teacher approved these changes

2019-07-28 08:57 UTC, merged