dz13 extra task complited
JerryMann/SkurkoAndroidPvt pull request #13
Opened 2019-08-16 07:41 UTC by JerryMann

2019-08-17 09:57 UTC, tim-teacher requested changes

2019-08-17 09:57 UTC, jushlwest commented on app/src/test/java/by/itacademy/pvt/skurkoandroidpvt/Dz13Test.kt
> +    fun testCheckWin() {
если не ошибаюсь там в задании было 2 теста, добавьте оба и проверьте, что бы они оба выполнялись.

2019-08-18 08:04 UTC, JerryMann commented on app/src/test/java/by/itacademy/pvt/skurkoandroidpvt/Dz13Test.kt
> +    fun testCheckWin() {
Все верно, просто я 2 теста в один метод поместил. Второй тест на 25 строке

2019-08-18 08:44 UTC, tim-teacher approved these changes

2019-08-18 08:44 UTC, jushlwest commented on app/src/test/java/by/itacademy/pvt/skurkoandroidpvt/Dz13Test.kt
> +    fun testCheckWin() {
аа ок, не посмотрел нормально, вообще лучше отдельными методами.

2019-08-18 08:45 UTC, eugenia-shumeika approved these changes

2019-08-18 11:25 UTC, JerryMann commented on app/src/test/java/by/itacademy/pvt/skurkoandroidpvt/Dz13Test.kt
> +    fun testCheckWin() {
ок, сделаю

2019-08-18 11:30 UTC, merged