Dz5
JerryMann/SkurkoAndroidPvt pull request #6
Opened 2019-06-29 10:51 UTC by JerryMann

![diagram](https://user-images.githubusercontent.com/49090476/60383064-f6dbe200-9a74-11e9-972d-833ef6dd90b1.jpg)

2019-06-30 16:42 UTC, tim-teacher requested changes

2019-06-30 16:42 UTC, jushlwest commented on app/src/main/java/by/itacademy/pvt/skurkoandroidpvt/dz5/Dz5OwlActivity.kt
> +        val owlAnimation = findViewById<ImageView>(R.id.dz5Owl)
Зачем findViewById каждый раз делать?

2019-07-01 07:15 UTC, eugenia-shumeika approved these changes

2019-07-01 10:31 UTC, stopstress approved these changes

2019-07-01 12:07 UTC, tim-teacher approved these changes

2019-07-02 14:35 UTC, merged